ALTER TABLE `gossip_menu_option`
	ADD COLUMN `OptionType` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `OptionBroadcastTextID`,
	ADD COLUMN `OptionNpcFlag` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `OptionType`;


REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 0, 0, 'GOSSIP_OPTION_QUESTGIVER', 0, 2, 2, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 1, 1, 'I want to browse your goods', 3370, 3, 128, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 2, 2, 'I want to travel fast', 0, 4, 8192, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 3, 3, 'Train me!', 3266, 5, 16, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 4, 4, 'Bring me back to life', 0, 6, 16384, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 5, 4, 'Bring me back to life', 0, 7, 32768, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 6, 5, 'Make this inn my home', 2822, 8, 65536, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 7, 6, 'Show me my bank', 0, 9, 131072, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 8, 7, 'How do I form a guild?', 3413, 10, 262144, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 9, 8, 'I want to create a guild crest', 3415, 11, 524288, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 10, 9, 'I want to join the Battle Ground', 0, 12, 1048576, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 11, 6, 'Auction!', 0, 13, 2097152, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 12, 0, 'I\'d like to stable my pet here', 8912, 14, 4194304, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 13, 1, 'I want to browse your goods', 3370, 15, 4096, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 14, 2, 'I wish to unlearn my talents', 8271, 16, 16, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 15, 2, 'I wish to unlearn my pet\'s skills', 0, 17, 16, 0, 0, 0, 0, 0, NULL, 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 16, 2, 'Purchase a Dual Talent Specialization', 33765, 18, 16, 0, 0, 0, 0, 100000, 'Are you sure you wish to purchase a Dual Talent Specialization?', 0, 0);
REPLACE INTO `gossip_menu_option` (`menuid`, `optionid`, `optionnpc`, `optiontext`, `optionbroadcasttextid`, `optiontype`, `optionnpcflag`, `LANGUAGE`, `actionmenuid`, `actionpoiid`, `boxcoded`, `boxmoney`, `boxtext`, `boxbroadcasttextid`, `verifiedbuild`) VALUES (0, 17, 0, 'GOSSIP_OPTION_OUTDOORPVP', 0, 19, 536870912, 0, 0, 0, 0, 0, NULL, 0, 0);
